### ISSUE TITLE
usb.busses returns generator - needs to be a list

### ISSUE THREAD

**Issue by kda** [markllama/powerusb#2]
I'm using a newer version of PyUSB (http://walac.github.io/pyusb/) and it seems that 'usb.busses' returns a generator rather than a list.  This simple patch seems to fix it for me.

```
diff --git a/powerusb/hidapi.py b/powerusb/hidapi.py
index e8e47322559c..a0d49c2a1c03 100644
--- a/powerusb/hidapi.py
+++ b/powerusb/hidapi.py
@@ -68,7 +68,7 @@ def hid_enumerate(vendor_id, product_id):
     hid_devices = []

-    busses = usb.busses()
+    busses = list(usb.busses())

     # check each bus
     for b_index in range(0, len(busses)):
```

**Comment by dirtbirb** [comment]
Worked for me, thanks! Using latest version of PyUSB as of this post.

**Comment by markllama** [comment]
Wow, I'm glad! It's been a long time since I worked on this. It's nice to
know people are still finding it and using it. Enjoy!

**Comment by dirtbirb** [comment]
I made the change and submitted a pull request. Still learning Git, please let me know if there was a more direct way to attach the pull request to this issue! (Or if a pull request is even necessary for such a simple change)

**Comment by markllama** [comment]
Closed by contributed PR.  Thank you!
