### ISSUE TITLE
Crashes when a kernel driver has claimed the interface

### ISSUE THREAD

**Issue by ChristopherNeufeld** [markllama/powerusb#4]
I recently plugged in a new USB wireless keyboard, and the powerusb script stopped working.  The kernel HID driver was now claiming the powerusb interface, and so an exception was raised when the script tried to claim the interface.
I fixed the issue for myself with:
```diff
diff --git a/powerusb/hidapi.py b/powerusb/hidapi.py
index f697456..054e7dc 100644
--- a/powerusb/hidapi.py
+++ b/powerusb/hidapi.py
@@ -138,6 +138,10 @@ class HIDDevice():
 
     def open(self):
         self.dh = self.usb_device.open()
+       try:
+           self.dh.detachKernelDriver(0)
+       except:
+           pass
         self.dh.claimInterface(0)
 
     def close(self):
```
A better patch would record whether the detach was successful, and reattach it upon exit, but I am not familiar enough with Python to be confident of doing that.

**Comment by markllama** [comment]
I used this verbatim.  I agree, there must be a better way.
